name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
