name: Unit Tests

on:
  pull_request: 
  pull_request_target:

jobs:
  unit-test-job:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set-up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Unit tests
        run: bash ./gradlew test

      - name: Upload Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Unit-Test-Reports
          path: |
            **/build/test-results/*UnitTest

      - name: Create Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Report
          reporter: java-junit
          path: |
            **/build/test-results/*UnitTest/*.xml
